CREATE DATABASE IF NOT EXISTS business;
CREATE DATABASE IF NOT EXISTS chatbot;
CREATE DATABASE IF NOT EXISTS batch;
CREATE DATABASE IF NOT EXISTS bank;
CREATE DATABASE IF NOT EXISTS alarm;

-- GRANT ALL PRIVILEGES ON *.* TO 'chunsun'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;