CREATE DATABASE IF NOT EXISTS business;
CREATE DATABASE IF NOT EXISTS chatbot;
CREATE DATABASE IF NOT EXISTS batch;
CREATE DATABASE IF NOT EXISTS bank;
CREATE DATABASE IF NOT EXISTS alarm;

CREATE USER 'aicheck603'@'%' IDENTIFIED BY 'ssafy1357';
GRANT ALL PRIVILEGES ON *.* TO 'aicheck603'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;