#!/bin/bash

echo "[Init] MySQL 초기화 시작..."

# 환경 변수 확인
echo "[Init] MYSQL_USERNAME=${MYSQL_USERNAME}"
echo "[Init] MYSQL_PASSWORD=********"
echo "[Init] MYSQL_ROOT_PASSWORD=********"

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS business;
CREATE DATABASE IF NOT EXISTS chatbot;
CREATE DATABASE IF NOT EXISTS batch;
CREATE DATABASE IF NOT EXISTS bank;
CREATE DATABASE IF NOT EXISTS alarm;

CREATE USER IF NOT EXISTS '${MYSQL_USERNAME}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USERNAME}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

echo "[Init] MySQL 초기화 완료 ✅"